//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedRiverTechnicalWebApp {
    
    
    public partial class RecipeDropdown {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Holds the form with all fields.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// RecipeDropdownList control.
        /// </summary>
        /// <remarks>
        /// Dropdown list with the recipe options: Lemon Tea, Coffee, or Chocolate.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList RecipeDropdownList;
        
        /// <summary>
        /// submit1 control.
        /// </summary>
        /// <remarks>
        /// Button that submits the form.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button submit1;
        
        /// <summary>
        /// L1 control.
        /// </summary>
        /// <remarks>
        /// Label that tells user what drink they selected.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label L1;
        
        /// <summary>
        /// Step1 control.
        /// </summary>
        /// <remarks>
        /// The first step in the recipe process, dependent on 
        /// user selection
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Step1;

        /// <summary>
        /// Step2 control.
        /// </summary>
        /// <remarks>
        /// The second step in the recipe process, dependent on 
        /// user selection
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Step2;

        /// <summary>
        /// Step3 control.
        /// </summary>
        /// <remarks>
        /// The third step in the recipe process, dependent on 
        /// user selection
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Step3;

        /// <summary>
        /// Step4 control.
        /// </summary>
        /// <remarks>
        /// The fourth step in the recipe process, dependent on 
        /// user selection. Does not appear if Chocolate was selected.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Step4;
    }
}
